#!/bin/bash

echo "All variables passed to the script: $@"
#  Result:  sh 09-special-vars Maha 10 !
#           All variables passed to the script: Maha 10 !

echo "Number of variables passed to the script: $#"
#  Result:  sh 09-special-vars Maha 10 !
#           Number of variables passed to the script: 3"

echo "To know the script name: $0"
# Result: To know the script name: 09-special-vars

echo "To know the current working directory: $PWD"
# Result: To know the current working directory:

echo "To know the home user directory: $HOME"
#RESULT: To know the home user directory: /home/ec2-user

echo "PID of the script executing now: $$"
# RESULT: PID of the script executing now: 1993


